<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default</name>
  <uuid>c5eebc67-f348-451e-96bf-3fef9c2d140e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[then set decision to basic ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
