<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>75ea8ab8-b4ad-47c5-8786-46caa5e453a2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to member ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
