<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>aab6a32f-5ead-4d27-8901-a6f9530f335d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to member ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
